"""Removed user_role_association

Revision ID: 85fa9f2dfb7c
Revises: e05d432f6d36
Create Date: 2024-12-10 08:42:32.177828

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85fa9f2dfb7c'
down_revision = 'e05d432f6d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_role_association_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_role_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_role_association_pkey')
    )
    # ### end Alembic commands ###
