"""Updated models for team permissions

Revision ID: 61fadb1865f7
Revises: 85fa9f2dfb7c
Create Date: 2024-12-20 04:35:08.020993

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61fadb1865f7'
down_revision = '85fa9f2dfb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('teams_pkey')),
    sa.UniqueConstraint('name', name=op.f('teams_name_key'))
    )
    op.create_table('teams_permissions_association',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('teams_permissions_association_permission_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('teams_permissions_association_team_id_fkey')),
    sa.PrimaryKeyConstraint('team_id', 'permission_id', name=op.f('teams_permissions_association_pkey'))
    )
    op.create_table('users_teams_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('users_teams_association_team_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_teams_association_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('users_teams_association_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_teams_association')
    op.drop_table('teams_permissions_association')
    op.drop_table('teams')
    # ### end Alembic commands ###
